# Generated by Django 2.0.2 on 2018-05-04 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumed_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count1', models.IntegerField(default=1)),
                ('count2', models.IntegerField(default=0)),
                ('count3', models.IntegerField(default=0)),
                ('count4', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryItem')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Stamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.datetime(2018, 5, 4, 9, 47, 34, 196292, tzinfo=utc))),
            ],
        ),
    ]
