# Generated by Django 2.0.2 on 2018-04-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumed_stats',
            old_name='food_item',
            new_name='food',
        ),
    ]
