# Generated by Django 2.0.2 on 2018-05-04 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_stamp',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 5, 4, 5, 18, 8, 794703, tzinfo=utc)),
        ),
    ]
