# Generated by Django 2.0.2 on 2018-05-05 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20180505_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_stamp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 4, 12, 59, 74199, tzinfo=utc)),
        ),
    ]
