# Generated by Django 2.0.4 on 2018-04-29 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_consumed_stats_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumed_stats',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryItem'),
        ),
    ]
