# Generated by Django 2.0.2 on 2018-05-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20180505_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_stamp',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
