# Generated by Django 2.0.4 on 2018-05-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180502_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=13),
            preserve_default=False,
        ),
    ]
