# Generated by Django 2.0.2 on 2018-05-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180503_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
