# Generated by Django 2.0.2 on 2018-05-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180504_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
