# Generated by Django 2.0.2 on 2018-05-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('barcode', models.CharField(blank=True, max_length=13)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='groceryitems',
            name='groceryList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryList.GroceryList'),
        ),
        migrations.AddField(
            model_name='groceryitems',
            name='inventoryItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryItem'),
        ),
    ]
