# Generated by Django 2.0.1 on 2018-02-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryList', '0002_auto_20180209_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='lists',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='lists',
            field=models.ManyToManyField(to='groceryList.GroceryList'),
        ),
    ]
