# Generated by Django 2.0.1 on 2018-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryList', '0005_auto_20180220_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='fooditems',
            field=models.ManyToManyField(to='groceryList.FoodItem'),
        ),
    ]
