# Generated by Django 2.0.1 on 2018-02-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryList', '0006_grocerylist_fooditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='lists',
        ),
    ]
