# Generated by Django 2.0.1 on 2018-02-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryList', '0007_remove_fooditem_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='lists',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='recipes',
            field=models.ManyToManyField(to='groceryList.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fooditems',
            field=models.ManyToManyField(to='groceryList.FoodItem'),
        ),
    ]
