# Generated by Django 2.0.1 on 2018-02-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryList', '0008_auto_20180223_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
