# Generated by Django 2.0.2 on 2018-04-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryList', '0010_auto_20180226_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='fooditems',
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='recipes',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
