# Generated by Django 2.0.2 on 2018-05-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryList', '0011_auto_20180423_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='barcode',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
