# Generated by Django 2.0.2 on 2018-04-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceryList', '0011_auto_20180423_1128'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityAndName', models.CharField(max_length=100)),
                ('foodItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryList.FoodItem')),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='yummlyRecipeId',
            new_name='yummlyId',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='recipeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
