# Generated by Django 2.0.2 on 2018-04-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20180423_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='quantityAndName',
            new_name='ingredient',
        ),
    ]
