# Generated by Django 2.0.2 on 2018-04-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20180424_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='externalLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
