# Generated by Django 2.0.2 on 2018-04-25 23:06

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20180424_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.user_directory_path),
        ),
    ]
