# Generated by Django 2.0.4 on 2018-04-27 13:50

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.user_directory_path, validators=[recipes.models.Recipe.validate_image]),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='foodItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groceryList.FoodItem'),
        ),
    ]
