# Generated by Django 2.0.4 on 2018-04-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20180428_0014'),
        ('recipes', '0011_auto_20180428_2151'),
    ]

    operations = [
    ]
