# Generated by Django 2.0.2 on 2018-04-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_merge_20180429_2040'),
        ('recipes', '0016_auto_20180429_2327'),
    ]

    operations = [
    ]
